# Generated by Django 5.1 on 2024-08-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0002_remove_usuario_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCatalogo.livro'),
        ),
    ]
