# Generated by Django 5.1 on 2024-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0003_usuario_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_publi',
            field=models.CharField(max_length=20),
        ),
    ]
